package com.crm_for_bot.entity;

import jakarta.persistence.*;
import lombok.Data;
import lombok.Getter;

import java.util.Set;

/**
 * Entity representing a role in the application.
 * Used to define and manage roles assigned to users.
 */
@Data
@Entity
@Table(name = "roles")
@Getter
public class Role {

    /**
     * The unique identifier for the role.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The name of the role.
     * This field must be unique and cannot be null.
     */
    @Column(nullable = false, unique = true)
    private String name;

    /**
     * The set of users associated with this role.
     * This field is fetched eagerly to ensure roles are loaded with users.
     */
    @ManyToMany(mappedBy = "roles", fetch = FetchType.EAGER)
    private Set<User> users;
}
