telegram:
  bot:
    username: ${BOT_NAME}
    token: ${BOT_TOKEN}


link:
  address: ${REST_SERVICE_URL}

spring:
  dotenv:
    enabled: true
  datasource:
    url: jdbc:postgresql://database:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

salt: ${SALT}



